name: FaceXHuBERT
channels:
  - defaults
  - conda-forge
dependencies:
  - argon2-cffi=20.1.0=py38h2bbff1b_1
  - async_generator=1.10=pyhd3eb1b0_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - bleach=4.0.0=pyhd3eb1b0_0
  - ca-certificates=2021.10.26=haa95532_2
  - certifi=2021.10.8=py38haa95532_2
  - cffi=1.15.0=py38h2bbff1b_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - console_shortcut=0.1.1=4
  - debugpy=1.5.1=py38hd77b12b_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.3=py38_0
  - importlib-metadata=4.8.2=py38haa95532_0
  - importlib_metadata=4.8.2=hd3eb1b0_0
  - ipykernel=6.4.1=py38haa95532_1
  - ipython=7.29.0=py38hd4e2768_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.18.0=py38haa95532_1
  - jsonschema=3.2.0=pyhd3eb1b0_2
  - jupyter_client=7.1.0=pyhd3eb1b0_0
  - jupyter_core=4.9.1=py38haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=2.0.1=py38h2bbff1b_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mistune=0.8.4=py38he774522_1000
  - msys2-conda-epoch=20160418=1
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - notebook=6.4.6=py38haa95532_0
  - openssl=1.1.1m=h2bbff1b_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandocfilters=1.4.3=py38haa95532_1
  - parso=0.8.3=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=21.2.2=py38haa95532_0
  - prometheus_client=0.12.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.10.0=pyhd3eb1b0_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyrsistent=0.18.0=py38h196d8e1_0
  - python=3.8.12=h6244533_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pywin32=302=py38h827c3e9_1
  - pywinpty=0.5.7=py38_0
  - pyzmq=22.3.0=py38hd77b12b_2
  - send2trash=1.8.0=pyhd3eb1b0_1
  - sqlite=3.37.0=h2bbff1b_0
  - terminado=0.9.4=py38haa95532_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - tornado=6.1=py38h2bbff1b_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py38_1
  - wheel=0.37.0=pyhd3eb1b0_1
  - wincertstore=0.2=py38haa95532_2
  - winpty=0.4.3=4
  - zipp=3.6.0=pyhd3eb1b0_0
  - pip:
    - absl-py==0.15.0
    - ansiwrap==0.8.4
    - anyio==3.6.1
    - astunparse==1.6.3
    - babel==2.10.3
    - beautifulsoup4==4.11.1
    - biopython==1.79
    - cachetools==4.2.4
    - click==8.1.1
    - configparser==5.2.0
    - cycler==0.11.0
    - decorator==4.4.2
    - deprecation==2.1.0
    - et-xmlfile==1.1.0
    - fastjsonschema==2.15.3
    - ffmpeg-python==0.2.0
    - filelock==3.6.0
    - fonttools==4.28.5
    - freetype-py==2.2.0
    - future==0.18.2
    - fvcore==0.1.5.post20220305
    - google-auth==2.3.3
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.43.0
    - h5py==2.10.0
    - huggingface-hub==0.0.8
    - hyperpyyaml==1.0.1
    - imageio==2.16.1
    - imageio-ffmpeg==0.4.7
    - iopath==0.1.9
    - ipywidgets==7.7.0
    - jinja2==3.1.2
    - json5==0.9.8
    - jsonlines==3.0.0
    - jupyter-packaging==0.12.2
    - jupyter-server==1.17.1
    - jupyterlab==3.4.3
    - jupyterlab-server==2.14.0
    - jupyterlab-widgets==1.1.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.2
    - librosa==0.8.1
    - markdown==3.3.6
    - matplotlib==3.5.1
    - nbclassic==0.3.7
    - nbconvert==6.5.0
    - nbformat==5.4.0
    - networkx==2.7.1
    - notebook-shim==0.1.0
    - numpy==1.20.0
    - oauthlib==3.1.1
    - opencv-python==4.5.5.62
    - openpyxl==3.0.9
    - opt-einsum==3.3.0
    - pandas==1.3.5
    - pandas-stubs==1.2.0.57
    - pillow==9.0.0
    - portalocker==2.4.0
    - praatio==5.1.1
    - proglog==0.1.10
    - protobuf==3.19.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyglet==1.5.26
    - pymeshlab==0.2.1
    - pymysql==1.0.2
    - pyopengl==3.1.0
    - pyrender==0.1.45
    - pytz==2021.3
    - pyyaml==6.0
    - regex==2022.3.15
    - requests==2.28.0
    - requests-oauthlib==1.3.0
    - rsa==4.8
    - ruamel-yaml==0.17.21
    - ruamel-yaml-clib==0.2.6
    - sacremoses==0.0.49
    - sentencepiece==0.1.96
    - setuptools==62.6.0
    - shutils==0.1.0
    - six==1.15.0
    - sniffio==1.2.0
    - soupsieve==2.3.2.post1
    - tabulate==0.8.9
    - termcolor==1.1.0
    - textwrap3==0.9.2
    - tinycss2==1.1.1
    - tokenizers==0.10.3
    - tomlkit==0.11.0
    - tqdm==4.63.0
    - transformers==4.7.0
    - trimesh==3.12.6
    - typing-extensions==4.0.1
    - urllib3==1.26.8
    - websocket-client==1.3.3
    - werkzeug==2.0.2
    - widgetsnbextension==3.6.0
    - yacs==0.1.8
    
